import * as React from "react";
import type { IChatbotEmbedProps } from "./IChatbotEmbedProps";

export default class ChatbotEmbed extends React.Component<IChatbotEmbedProps> {
  private containerId = "chatbot-embed-container";

  public componentDidMount(): void {
    this._injectWidget().catch(console.error);
  }

  public componentDidUpdate(prevProps: IChatbotEmbedProps): void {
    if (prevProps.widgetBaseUrl !== this.props.widgetBaseUrl) {
      // Re-inject if the URL changes
      this._injectWidget().catch(console.error);
    }
  }

  private async _injectWidget(): Promise<void> {
    const { widgetBaseUrl } = this.props;

    if (!widgetBaseUrl) {
      console.warn(
        "[ChatbotEmbed] No widgetBaseUrl provided. Widget will not load.",
      );
      return;
    }

    // Set a global variable so that the widget knows its own base URL for API calls etc.
    if (typeof window !== "undefined") {
      (window as any).__BACKEND_API_URL__ = widgetBaseUrl;
      (window as any).__USER_EMAIL__ = this.props.userEmail;
    }

    try {
      // Fetch the EMBED index.html generated by Vite (/embed/index.html instead of /widget/index.html)
      const response = await fetch(`${widgetBaseUrl}/embed/index.html`);
      const htmlText = await response.text();

      // Parse the HTML to extract the asset links
      const parser = new DOMParser();
      const doc = parser.parseFromString(htmlText, "text/html");

      // 1. Inject CSS Links
      const links = doc.querySelectorAll('link[rel="stylesheet"]');
      links.forEach((link) => {
        const href = link.getAttribute("href");
        if (href) {
          // Resolve relative href to absolute URL
          const absoluteUrl = new URL(href, `${widgetBaseUrl}/embed/`).href;
          if (!document.querySelector(`link[href="${absoluteUrl}"]`)) {
            const newLink = document.createElement("link");
            newLink.rel = "stylesheet";
            newLink.href = absoluteUrl;
            document.head.appendChild(newLink);
          }
        }
      });

      // 2. Inject Module Preloads
      const preloads = doc.querySelectorAll('link[rel="modulepreload"]');
      preloads.forEach((link) => {
        const href = link.getAttribute("href");
        if (href) {
          const absoluteUrl = new URL(href, `${widgetBaseUrl}/embed/`).href;
          if (!document.querySelector(`link[href="${absoluteUrl}"]`)) {
            const newLink = document.createElement("link");
            newLink.rel = "modulepreload";
            newLink.href = absoluteUrl;
            document.head.appendChild(newLink);
          }
        }
      });

      // 3. Inject Scripts
      const scripts = doc.querySelectorAll("script");
      scripts.forEach((script) => {
        const src = script.getAttribute("src");
        if (src) {
          const absoluteUrl = new URL(src, `${widgetBaseUrl}/embed/`).href;
          if (!document.querySelector(`script[src="${absoluteUrl}"]`)) {
            const newScript = document.createElement("script");
            newScript.src = absoluteUrl;
            newScript.type = script.getAttribute("type") || "text/javascript";
            newScript.async = true;
            newScript.crossOrigin = script.getAttribute("crossOrigin") || "";
            
            newScript.onload = () => {
              if (typeof (window as any).mountChatbotEmbed === "function") {
                (window as any).mountChatbotEmbed(this.containerId);
              }
            };
            document.body.appendChild(newScript);
          } else {
             if (typeof (window as any).mountChatbotEmbed === "function") {
                (window as any).mountChatbotEmbed(this.containerId);
             }
          }
        }
      });

    } catch (error: any) {
      console.error("[ChatbotEmbed] Failed to inject widget assets from index.html", error);
    }
  }

  public render(): React.ReactElement<IChatbotEmbedProps> {
    const { hasTeamsContext, widgetBaseUrl } = this.props;

    return (
      <section className={`${hasTeamsContext ? "teams-context" : "sp-context"}`}>
        {/* Placeholder container where the React 19 bot will be mounted natively */}
        <div 
           id={this.containerId} 
           style={{  
             minHeight: '600px', 
             width: '100%',
             position: 'relative',
             display: 'block'
           }}
        ></div>
      </section>
    );
  }
}
