import * as React from "react";
import type { IChatbotProps } from "./IChatbotProps";

export default class Chatbot extends React.Component<IChatbotProps> {
  private containerId = "chatbot-widget-container";

  public componentDidMount(): void {
    this._injectWidget().catch(console.error);
  }

  public componentDidUpdate(prevProps: IChatbotProps): void {
    if (prevProps.widgetBaseUrl !== this.props.widgetBaseUrl) {
      // Re-inject if the URL changes
      this._injectWidget().catch(console.error);
    }
  }

  private async _injectWidget(): Promise<void> {
    const { widgetBaseUrl } = this.props;

    if (!widgetBaseUrl) {
      console.warn(
        "[ChatbotWebPart] No widgetBaseUrl provided. Widget will not load.",
      );
      return;
    }

    // Set a global variable so that the widget knows its own base URL for API calls etc.
    if (typeof window !== "undefined") {
      (window as any).__BACKEND_API_URL__ = widgetBaseUrl;
      (window as any).__USER_EMAIL__ = this.props.userEmail;
    }

    try {
      // Fetch the index.html generated by Vite
      const response = await fetch(`${widgetBaseUrl}/widget/index.html`);
      const htmlText = await response.text();

      // Parse the HTML to extract the asset links
      const parser = new DOMParser();
      const doc = parser.parseFromString(htmlText, "text/html");

      // 1. Inject CSS Links
      const links = doc.querySelectorAll('link[rel="stylesheet"]');
      links.forEach((link) => {
        const href = link.getAttribute("href");
        if (href) {
          // Resolve relative href to absolute URL
          const absoluteUrl = new URL(href, `${widgetBaseUrl}/widget/`).href;
          if (!document.querySelector(`link[href="${absoluteUrl}"]`)) {
            const newLink = document.createElement("link");
            newLink.rel = "stylesheet";
            newLink.href = absoluteUrl;
            document.head.appendChild(newLink);
          }
        }
      });

      // 2. Inject Module Preloads (Optional but good for performance)
      const preloads = doc.querySelectorAll('link[rel="modulepreload"]');
      preloads.forEach((link) => {
        const href = link.getAttribute("href");
        if (href) {
          const absoluteUrl = new URL(href, `${widgetBaseUrl}/widget/`).href;
          if (!document.querySelector(`link[href="${absoluteUrl}"]`)) {
            const newLink = document.createElement("link");
            newLink.rel = "modulepreload";
            newLink.href = absoluteUrl;
            document.head.appendChild(newLink);
          }
        }
      });

      // 3. Inject Scripts
      const scripts = doc.querySelectorAll("script");
      scripts.forEach((script) => {
        const src = script.getAttribute("src");
        if (src) {
          const absoluteUrl = new URL(src, `${widgetBaseUrl}/widget/`).href;
          if (!document.querySelector(`script[src="${absoluteUrl}"]`)) {
            const newScript = document.createElement("script");
            newScript.src = absoluteUrl;
            newScript.type = script.getAttribute("type") || "text/javascript";
            newScript.async = true;
            newScript.crossOrigin = script.getAttribute("crossOrigin") || "";
            
            newScript.onload = () => {
              if (typeof (window as any).mountChatbotWidget === "function") {
                (window as any).mountChatbotWidget(this.containerId);
              }
            };
            document.body.appendChild(newScript);
          } else {
             if (typeof (window as any).mountChatbotWidget === "function") {
                (window as any).mountChatbotWidget(this.containerId);
             }
          }
        }
      });

    } catch (error) {
      console.error("[ChatbotWebPart] Failed to inject widget assets from index.html", error);
    }
  }

  public render(): React.ReactElement<IChatbotProps> {
    return (
      <div id={this.containerId} style={{ padding: "20px", border: "1px dashed #ccc", borderRadius: "8px", textAlign: "center", color: "#666" }}>
        <strong>Chatbot Web Part</strong>
        <p style={{ fontSize: "12px", marginTop: "8px" }}>
          Widget Base URL: {this.props.widgetBaseUrl || "None"}<br/>
          (The floating chatbot icon will appear in the bottom-right corner if the script loads successfully)
        </p>
      </div>
    );
  }
}
